### ISSUE TITLE
Tests methods only checks response is a string and not equals to " "

### ISSUE THREAD

**Issue by pramodya1994** [wso2-ballerina/module-ethereum#17]
**Description:**
$Title
```ballerina
test:assertNotEquals(ethereumRes, " ", msg = "Failed to get version of Web3Client.");
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by wggihan** [comment]
This module is retired now.  This won't fix.
